-- ALIASES

-- COMMAND SHORTEN OR COLUMN NAME SHORTEN

-- ADVANTAGES
	-- WHEN MORE THAN ONE TABLES
    -- READABILITY
    -- TWO OR MORE COLUMS KO COMBINE KARNE MAI
    
USE COMPANYDB;

SELECT SSN, concat(FNAME,' ',LNAME) AS FULL_NAME
FROM
	EMPLOYEE;
    
SELECT 
	SSN, FNAME, SALARY, AVG(SALARY) 
    OVER( PARTITION BY DNO) AS AVG_SAL
FROM 
	EMPLOYEE
WHERE
	SALARY>AVG_SAL;
    
    -- CANT DO IT LIKE THIS WILL HAVE TO DO IT WITH INNER JOIN ONLY^^^^
    
-- LAG AND LEAD

SELECT 
	SSN, SALARY, FNAME,DNO,
   LAG(SALARY,1,0) OVER(PARTITION BY DNO ORDER BY SALARY)AS MINIMA 
FROM EMPLOYEE;

-- GAIN OF SALARY

SELECT SSN, FNAME, DNO, SALARY, 
SALARY-LAG(SALARY,1,0) OVER(PARTITION BY DNO ORDER BY SALARY) AS GAIN
FROM EMPLOYEE;

-- LEAD LAG KA BAS ULTA

-- PERCENTILES

SELECT SSN, FNAME, SALARY,DNO,
ROUND(percent_rank() OVER(partition by DNO ORDER BY SALARY),2) AS PERCENTILE
FROM EMPLOYEE;