-- FULL OUTER JOIN 
	-- WITH THE HELP OF UNION OPERATOR
    -- ABHI TAK SAARE EQUI JOINS THE
    
-- HEAVILY USED WHEN WORKING WITH TIMESTAMPS

-- NON EQUI JOINS


# EMPLOYEE AND THE SUPERVISOR NAME

SELECT 
    T1.SSN,
    CONCAT(T1.FNAME, ' ', T1.LNAME) AS EMPLOYEE,
    T2.SSN AS MANAGER_ID,
    CONCAT(T2.FNAME, ' ', T2.LNAME) AS MANAGER
FROM
    EMPLOYEE T1
        JOIN
    EMPLOYEE T2 ON T1.SUPER_SSN = T2.SSN AND T1.SUPER_SSN IS NOT NULL;
    
-- UNION
		-- STACK RESULTS ONE TBALE ON TOP OF ANOTHER
        
SELECT AVG(SALARY) OVER (PARTITION BY DNO), SEX FROM EMPLOYEE 
WHERE SEX='M'
UNION  
SELECT AVG(SALARY) OVER (PARTITION BY DNO) AS AVERAGE, SEX FROM EMPLOYEE 
WHERE SEX='F'