-- WINDOW FUNCTION
-- ACROSS A SET OF ROWS
-- USED FOR AGGREGATION AND RANKING

-- THE NO. OF ROWS DONT CHANGE UNLIKE 

USE COMPANYDB;

SELECT 
    DNO, AVG(SALARY)
FROM
    EMPLOYEE
GROUP BY DNO;

SELECT 
	DNO, AVG(SALARY) 
    OVER(PARTITION BY  DNO) AS AVG_SALARY
FROM
	EMPLOYEE;
    
-- WHEN TO USE WINDOW FUNCTION
	-- RUNNING PRICE, RUNING TOTAL ORDERS, RUNNING SUM SALES
    -- RANK
    -- MEASSURE TRENDS OR PATTERNS IN YOUR DATA
    -- RANKS OR PRIORITIZATION
    
-- CORE WINDOW FUNCTIONS

-- PARTITION BY
    
# COUNT EMPLOYEES IN EACH DEPARTMENT

-- DIFFERMECE BETWEEN GROUP BY AND WINDOW
	-- NUM OF ORWS

SELECT 
	FNAME,SSN,DNO,COUNT(SSN)
    OVER(PARTITION BY DNO) AS NUM_EMPLOYEES 
FROM
	EMPLOYEE;

-- CANT USE AGGGREGATORS N GORUP BYS ALONG WITH WINDOW FUNCTIONS

-- RANKING
-- ASSOCIATE RANK TO EACH N EVERY ROW

SELECT 
	SSN, SALARY, 
    RANK() OVER(ORDER BY SALARY DESC) AS SAL_RANK
FROM 
	EMPLOYEE;
    
-- DENSE RANK
	-- NEXT RANK = PREV RANK +1
    -- NORMAL RNAK JAISE NAHI
    
SELECT 
	SSN, DNO, SALARY,
    dense_rank() OVER(PARTITION BY DNO ORDER BY SALARY) AS RANK_SAL
FROM 
	EMPLOYEE;
    
-- ROW NUMBERS

SELECT 
	SSN, DNO, FNAME,
    row_number() OVER(PARTITION BY DNO) AS ROW_NUM
FROM 
	EMPLOYEE;


    